### ISSUE TITLE
Documentation is missing a list of actions you can execute on the browser

### ISSUE THREAD

**Issue by ingro** [assaf/zombie#958] opened 2015-10-27 09:41 UTC
Hello, I want to use this library to write some functional tests for a heave client-side project. Looking at the docs I didn't found anywhere how to, for example, click a link on the page, I had to dig the issues to find the right function.

I'm missing something or they are missing indeed?

**Comment by freewil** [comment] 2015-10-28 05:42
:+1: needs documentation

**Comment by askogvold** [comment] 2015-12-08 18:44
:+1:

**Comment by NeCkEr** [comment] 2015-12-16 12:06
+1

**Comment by cicloon** [comment] 2016-03-11 10:29
+1

**Comment by Bramanga** [comment] 2017-06-13 19:18
👍

**Comment by ForbesLindesay** [comment] 2017-06-22 02:20
Duplicate of #799

**Closed by ForbesLindesay** 2017-06-22 02:20 UTC
