### ISSUE TITLE
API Reference

### ISSUE THREAD

**Issue by z-vr** [assaf/zombie#977] opened 2015-11-27 10:26 UTC
Hi where can I find a documentation for all available methods such as 
browser.clickButton, browser.clickLink, browser.evaluate, etc? Those are the ones I saw on the Internet, but they are not described anywhere on the project's website. Many thanks.

**Comment by assaf** [comment] 2015-11-27 18:07
http://zombie.js.org and for the rest you'll have to read through the source code.

**Comment by z-vr** [comment] 2015-11-30 10:04
That's what I meant, there is no reference to clickButton on zombie.js.org. Will read through the source code then.

**Comment by ohenepee** [comment] 2015-12-02 14:45
devres.zoomquiet.io/data/20110811173813/index.html

BTW, assaf... its pretty embarrassing to direct/expect newbies to be reading source code...

**Comment by assaf** [comment] 2015-12-02 15:56
You're more than welcome to help and contribute some documentation

**Comment by alexserver** [comment] 2016-02-10 18:31
@z-vr here is the reference for pressButton https://github.com/assaf/zombie/blob/master/src/index.js#L929

@assaf , at least this one should be in the README, since it's in the examples...
You'll need some extra help as I've seen many unattended pull requests.

Great tool, though.

**Comment by ForbesLindesay** [comment] 2017-06-22 02:18
Duplicate of #799

**Closed by ForbesLindesay** 2017-06-22 02:18 UTC
