### ISSUE TITLE
Documentation for browser.wait()

### ISSUE THREAD

**Issue by Dygerati** [assaf/zombie#927] opened 2015-06-18 21:13 UTC
I'm attempting to simply fetch the value of a certain property on the window object after it's set. I found reference in a couple stackoverflow posts to a `browser.wait()` function that I may be able to use. This function definitely exists, but I can't find any documentation on it at all. 

Am I missing something?

**Comment by jws121295** [comment] 2016-08-01 20:23
Not sure who wrote this, but it has a more thorough documentation on the API:
http://zqdevres.qiniucdn.com/data/20110811173813/index.html
It might be for an older version of Zombie.js, so use at your own risk I guess.

I thought I was losing my mind with some mysteriously failing unit tests until I discovered people mentioning browser.wait()... but then I was confused why there wasn't full documentation on its main page!

**Comment by ForbesLindesay** [comment] 2017-06-22 02:19
Duplicate of #799

**Closed by ForbesLindesay** 2017-06-22 02:19 UTC
