### ISSUE TITLE
Reporting errors with silent=true

### ISSUE THREAD

**Issue by wernight** [assaf/zombie#878] opened 2015-03-12 08:17 UTC
I've set `browser.silent = true;` but while testing PayPal payment I still see errors being reported; shouldn't they be ignored?

````
Error: [$rootScope:infdig] http://errors.angularjs.org/1.3.9/$rootScope/infdig?p0=10&p1=%5B%5D
      at Error (<anonymous>)
      at https://www.paypalobjects.com/web/res/371/957e19d6ef85178c220d8001afcfa/js/framework.js:6:416
      at l.$digest (https://www.paypalobjects.com/web/res/371/957e19d6ef85178c220d8001afcfa/js/framework.js:124:366)
      at https://www.paypalobjects.com/web/res/371/957e19d6ef85178c220d8001afcfa/js/framework.js:126:280
      at e (https://www.paypalobjects.com/web/res/371/957e19d6ef85178c220d8001afcfa/js/framework.js:40:339)
      at https://www.paypalobjects.com/web/res/371/957e19d6ef85178c220d8001afcfa/js/framework.js:44:375
      at window._evaluate (/code/node_modules/zombie/lib/document.js:437:23)
      at /code/node_modules/zombie/lib/eventloop.js:65:33
      at Object._onImmediate (/code/node_modules/zombie/lib/eventloop.js:609:11)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
````

Using Zombie snapshot [version 3.0.14](https://github.com/assaf/zombie/commit/3ebc0e99314f00b420427ac717f90bcc543f96fb).

**Comment by wernight** [comment] 2015-03-12 10:44
Actually the initial PayPal page is a really good page to check all kind of weird behaviors and probably fix some in Zombie. I get all kinds of errors:

* The one above
* An error occurred: RangeError: Maximum call stack size exceeded
* Error: Timeout: did not get to load all resources on this page `at [object Object].timeout (/code/node_modules/zombie/lib/eventloop.js:543:36)`
* TypeError: Cannot call method 'indexOf' of undefined
      at s_gi (https://www.paypalobjects.com/js/site_catalyst/pp_jscode_080706.js:904:66)
      at https://www.paypalobjects.com/js/site_catalyst/pp_jscode_080706.js:6:7
      in https://www.paypal.com/checkoutnow/2?fallback=1&token=EC-8WX32565XY650643F
* ...

**Comment by assaf** [comment] 2015-03-12 15:13
The `silent` flag suppresses `console.log` output, nothing to do with errors.

Errors propagate through the API and generally reported by not catching them.

**Comment by wernight** [comment] 2015-03-12 15:45
Is there a way to ignore them for a certain time, website... ?

**Comment by assaf** [comment] 2015-03-12 15:48
Catch the error.

**Comment by wernight** [comment] 2015-03-12 16:11
I was trying
I was trying

    browser.pressButton('input[name="paypal"]')
      .catch(Error, function(e) {});

but it seems to work most of the time only with:

    try {
      browser
        .pressButton('input[name="paypal"]')
        .catch(Error, function(e) {});
    } catch (err) {
    }

However it seems that it's still pretty flaky and for example `browser.assert.url` fail because something is `undefined`. Seems that Zombie doesn't finish processed if one of those errors occur.

**Comment by assaf** [comment] 2015-03-12 16:22
The timeout error you reported above happens asynchronously, so try/catch has no affect. But `pressButton` can also trigger DOM event handlers, and those errors happen synchronously.

Generally errors will stop processing, and so you need to catch the error and continue. That's by design. Zombie is a testing tool, and you want errors to fail your tests.

**Comment by wernight** [comment] 2015-03-12 16:33
I agree that by default it should do that, but in some cases you're going through externally hosted websites (like PayPal, to test for example payment flow). On those you don't want to report most errors.

**Comment by assaf** [comment] 2015-03-12 16:51
I don't recommend running Zombie against PayPal. If you need to test a flow that involves visiting PayPal, you can mock the entry/exit points using libraries like nock or node-replay. You get faster and more dependable tests.

**Comment by wernight** [comment] 2015-03-12 16:56
That will not guarantee that it works. PayPal has sandbox mode which is designed for testing. Other cases include that the API should perform some HTTP request on success for example, and to make sure those work, you have to use the external API.

Now if Zombie cannot do that, I'll have to go back to WebDriver tests which are fine, just a lot more heavy.

**Comment by assaf** [comment] 2015-03-15 01:19
I'm closing this, since problem is with the application not catching errors.

**Closed by assaf** 2015-03-15 01:19 UTC

**Comment by pronebird** [comment] 2015-08-16 23:38
so how do you catch those punks?
